server:
  port: 9090

spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:menu;
    username: sa
    password: asdqwe123

  jpa:
    open-in-view: false
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      show-sql: true
      format_sql: true

  sql:
    init:
      mode: embedded
      schema-locations: classpath*:/sql/schema.sql
      data-locations: classpath*:/sql/data.sql